# Generated by Django 4.2.6 on 2023-10-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
